In [12]:
import pandas as pd
import sklearn
import matplotlib
import matplotlib.pyplot as plt
import itertools

train = pd.read_csv("C:/Users/sebaa/OneDrive/Studies/Thesis_RISE_2021/Thesis_ML_impl/labelled1.csv")

# Distribution of normal and anomaly traffic in train data
print(train['class'].value_counts())

#features = train.columns.tolist()
#features.remove('timestamp'), features.remove('class'), features.remove('attack_type')

#PREPROCESSING
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# extract numerical attributes and scale it to have zero mean and unit variance  
cols = train.select_dtypes(include=['float64','int64']).columns
sc_train = scaler.fit_transform(train.select_dtypes(include=['float64','int64']))
# turn the result back to a dataframe
train_x = pd.DataFrame(sc_train, columns = cols)
train_y = train['class']
print(train_x.shape)
print(train_y.shape)

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(train_x,train_y,train_size=0.70, random_state=1, stratify=train_y)

from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier

#RandomForest classifier
clf1= OneVsRestClassifier(RandomForestClassifier(random_state=1))
#Gradient Boost
clf2 = OneVsRestClassifier(GradientBoostingClassifier())
#DTC
clf4 = OneVsRestClassifier(DecisionTreeClassifier())
#ANN
clf5 = OneVsRestClassifier(MLPClassifier(solver='lbfgs', max_iter = 5000))
#Naive Bayes
clf6 = GaussianNB()
#SVM
svm_model = svm.SVC(kernel='linear')
clf7 = OneVsOneClassifier(svm_model)
#LR
clf8 = OneVsRestClassifier(LogisticRegression(random_state=0))
#KNN
clf9 = OneVsRestClassifier(KNeighborsClassifier())

labels = [('rf', clf1), ('gb', clf2), ('dtc', clf4), ('mlp',clf5), ('gnb', clf6), ('svm', clf7), ('lr', clf8), 
          ('knn', clf9)]
'''
for i in list(itertools.combinations(labels,2)):
    print(list(i))

    eclf = VotingClassifier(estimators=list(i), voting='soft')
    eclf.fit(X_train, Y_train)
    accuracy = metrics.accuracy_score(Y_test, eclf.predict(X_test))
    confusion_matrix = metrics.confusion_matrix(Y_test, eclf.predict(X_test))
    classification = metrics.classification_report(Y_test, eclf.predict(X_test)) 
    print()
    print('============================== Model Test Results ==============================')
    print()
    print ("Model Accuracy:" "\n", accuracy)
    print()
    print("Confusion matrix:" "\n", confusion_matrix)
    print()
    print("Classification report:" "\n", classification) 
    print()
'''
eclf = VotingClassifier(estimators=[('gb',clf2), ('dtc',clf4), ('gnb', clf6)], voting='soft')
eclf.fit(X_train, Y_train)
accuracy = metrics.accuracy_score(Y_test, eclf.predict(X_test))
confusion_matrix = metrics.confusion_matrix(Y_test, eclf.predict(X_test), normalize='true')
classification = metrics.classification_report(Y_test, eclf.predict(X_test)) 
print()
print('============================== Model Test Results ==============================')
print()
print ("Model Accuracy:" "\n", accuracy)
print()
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 
print()


normal                  1920
Scaling                  434
Data tampering           227
DoS                       88
False data injection      36
Name: class, dtype: int64
(2705, 4)
(2705,)

============================== Model Test Results ==============================

Model Accuracy:
 0.9051724137931034

Confusion matrix:
 [[0.66176471 0.         0.         0.11764706 0.22058824]
 [0.         1.         0.         0.         0.        ]
 [0.         0.         0.90909091 0.09090909 0.        ]
 [0.1        0.         0.         0.71538462 0.18461538]
 [0.02430556 0.         0.         0.00347222 0.97222222]]

Classification report:
                       precision    recall  f1-score   support

      Data tampering       0.62      0.66      0.64        68
                 DoS       1.00      1.00      1.00        27
False data injection       1.00      0.91      0.95        11
             Scaling       0.89      0.72      0.79       130
              normal       0.93      0.97    

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\multiclass.py:382: RuntimeWarning: invalid value encountered in true_divide
  Y /= np.sum(Y, axis=1)[:, np.newaxis]
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\multiclass.py:382: RuntimeWarning: invalid value encountered in true_divide
  Y /= np.sum(Y, axis=1)[:, np.newaxis]
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\multiclass.py:382: RuntimeWarning: invalid value encountered in true_divide
  Y /= np.sum(Y, axis=1)[:, np.newaxis]
